// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://riqievnbraelqrzrovyr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJpcWlldm5icmFlbHFyenJvdnlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3NTkzOTAsImV4cCI6MjA2NTMzNTM5MH0.zs6b1NxB_agh05yo3aaqA7e5ymZoKSjq6idqFZ_A5Wg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});